import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from lrc import *

lambdas = [0, 1e-7, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 1]

# generated by cross_validate.py
# alphs = [2e-2]
# lmbds = [1, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 0]
# grid_search(alphs, lmbds, train_data, train_labels, "graph_scores.npy")
# scores are in reverse order from the lambdas above

scores = np.load("graph_scores.npy")
scores[0] = scores[0][::-1]

'''
# plt.plot(lambdas, scores[0], label='Logistic Regression Classifier')
# plt.legend()
plt.plot(lambdas, scores[0])
plt.suptitle('L2 Lambda vs Accuracy')
plt.title("Mean Accuracy from 10-Fold Cross Validation", fontsize=10)
plt.xlabel('Lambda')
plt.ylabel('Accuracy')
plt.show()
'''

fig, axs = plt.subplots(1, 2)
fig.suptitle('L2 Lambda vs (10-fold mean) Accuracy')
axs[0].plot(lambdas, scores[0])
axs[0].set_title('Linear Scale')
axs[1].plot(lambdas, scores[0])
axs[1].set_xscale('log')
axs[1].set_title('Log Scale')
for ax in axs.flat:
	ax.set(xlabel='Lambda', ylabel='Accuracy')

plt.show()
