import pickle
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from lrc import *

lambdas = [0, 1e-7, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-2, 1e-1, 1]

# generated by cross_validate.py
# alphs = [2e-2]
# lmbds = [1, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 0]
# grid_search(alphs, lmbds, train_data, train_labels, "graph_scores.npy")
# scores are in reverse order from the lambdas above

scores = np.load("graph_scores.npy")
scores[0] = scores[0][::-1]

plt.plot(lambdas, scores[0], label='Logistic Regression Classifier')
plt.title('10-fold Cross-Validation mean accuracy ' +
          'with different L2 regularization coefficients')
plt.xlabel('lambda')
plt.ylabel('accuracy')
plt.legend()
plt.show()
